CREATE SCHEMA IF NOT EXISTS `1001DB` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `1001DB`.`Users` (
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Username` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(50) NOT NULL,
  `XP` INT NULL,
  `FieldOfStudy` VARCHAR(45) NULL,
  `TypeOfDegree` VARCHAR(45) NULL,
  `University` VARCHAR(45) NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB