import {StyleSheet} from 'react-native'

export default StyleSheet.create({
    title:{
        fontSize:30,
        color:'green',
        textAlign:'center',
        color:'#006622',
        fontWeight:'bold',
        padding:5
    },
    subtitle:{
        fontSize:18,
        color:'green',
        textAlign:'center',
        color:'#006622',
        padding:5
    },
    customContent:{
        flex:1,
        marginLeft:20,
        marginRight:20
    },
    customLogo:{
        flex:2
    },
    customLogin:{
        flex:1
    },
    details:{
        flex:1,
        justifyContent:'center',
        padding:4,
        alignItems:'center'
    },
    customSignup:{
        flex:1,
        justifyContent:'center',
    },
    customBottom:{
        flex:1
    },
    parent:{
        flex:1
    },
    loginButton:{
        backgroundColor:'green',
        borderColor:'#f5f5f5',
    },
    signupButton:{
        backgroundColor:'#f5f5f5',
        borderColor:'green',
    },
    button:{
        borderWidth:1,
        borderRadius:15,
        padding:15,
        justifyContent:'center'
    },
    heading:{
        fontSize:20,
        textAlign:'center'
    },
    loginText:{
        color:'#f5f5f5'
    }
})