import {StyleSheet} from 'react-native'

export default StyleSheet.create({
    heading:{
        fontSize:25,
        textAlign:'center'
    },
    input:{
        marginBottom:5,
        backgroundColor:'#f5f5f5'
    },
    customLogin:{
        flex:2,
        marginLeft:20,
        marginRight:20
    },
    customLogo:{
        flex:2
    },
    parent:{
        flex:1
    },
    loginButton:{
        backgroundColor:'green',
        borderColor:'#f5f5f5',
    },
    button:{
        borderWidth:1,
        borderRadius:20,
        padding:10,
        justifyContent:'center'
    },
    heading:{
        fontSize:20,
        textAlign:'center'
    },
    loginText:{
        color:'#f5f5f5'
    }
})